version: '3'

services:
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_password
      MYSQL_ROOT_HOST: '%'  # needs to be enclosed with quotes
    healthcheck:
            test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
            timeout: 20s
            retries: 10
    ports:
      - "3306:3306"

  myapp:
    image: devops-test
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=app_user
      - MYSQL_PASSWORD=app_password
      - MYSQL_DATABASE=mydatabase
    ports:
      - "3000:3000"
    depends_on:
      mysql:
        condition: service_healthy
